### ISSUE TITLE
Sensor value missing

### ISSUE THREAD

**Issue by NKV-obmc** [openbmc/phosphor-virtual-sensor#4]
Hi,

In virtual_sensor_config.json file, i added two DbusParam P0 and P1.
If two of the sensors are present it will show the total sum.
But if any of the sensor is absent sum is shown as null.
![image](https://user-images.githubusercontent.com/82563871/161476240-ce4b9b1b-a56f-4440-a8db-3e9e476c8b0a.png)

Regards
Nikhil

**Comment by NKV-obmc** [comment]
dbusSensor.hpp Modified

**Comment by iwoloschin** [comment]
How'd you modify dbusSensor.hpp? Just have it return `0` instead of `NaN`?

**Comment by NKV-obmc** [comment]
Yes, Changed the return value.
Instead of NaN

**Comment by williamspatrick** [comment]
Is there a code change that is useful to contribute back to the project?

**Comment by iwoloschin** [comment]
The naive "return 0 if sensor not found" work better in the cases I have, but probably not everywhere? Would you be open to the default value being settable as part of the JSON configuration, if unset keeping the current Quiet NaN value?
